2023-07-17 17:55:50,353 INFO    StreamThr :24552 [internal.py:wandb_internal():86] W&B internal server running at pid: 24552, started at: 2023-07-17 17:55:50.352793
2023-07-17 17:55:50,366 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: status
2023-07-17 17:55:50,367 INFO    WriterThread:24552 [datastore.py:open_for_write():85] open: C:\Users\motom\Desktop\Python\Sputnik_VAE\wandb\run-20230717_175550-03q3v84h\run-03q3v84h.wandb
2023-07-17 17:55:50,380 DEBUG   SenderThread:24552 [sender.py:send():369] send: header
2023-07-17 17:55:50,380 DEBUG   SenderThread:24552 [sender.py:send():369] send: run
2023-07-17 17:55:51,234 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: check_version
2023-07-17 17:55:51,257 INFO    SenderThread:24552 [dir_watcher.py:__init__():211] watching files in: C:\Users\motom\Desktop\Python\Sputnik_VAE\wandb\run-20230717_175550-03q3v84h\files
2023-07-17 17:55:51,257 INFO    SenderThread:24552 [sender.py:_start_run_threads():1100] run started: 03q3v84h with start time 1689591350.363074
2023-07-17 17:55:51,258 DEBUG   SenderThread:24552 [sender.py:send_request():396] send_request: summary_record
2023-07-17 17:55:51,260 INFO    SenderThread:24552 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-17 17:55:51,261 DEBUG   SenderThread:24552 [sender.py:send_request():396] send_request: check_version
2023-07-17 17:55:51,797 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: run_start
2023-07-17 17:55:51,914 DEBUG   HandlerThread:24552 [system_info.py:__init__():31] System info init
2023-07-17 17:55:51,914 DEBUG   HandlerThread:24552 [system_info.py:__init__():46] System info init done
2023-07-17 17:55:51,914 INFO    HandlerThread:24552 [system_monitor.py:start():181] Starting system monitor
2023-07-17 17:55:51,915 INFO    SystemMonitor:24552 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-17 17:55:51,915 INFO    HandlerThread:24552 [system_monitor.py:probe():201] Collecting system info
2023-07-17 17:55:51,923 INFO    SystemMonitor:24552 [interfaces.py:start():190] Started cpu monitoring
2023-07-17 17:55:51,934 DEBUG   HandlerThread:24552 [system_info.py:probe():195] Probing system
2023-07-17 17:55:51,934 INFO    SystemMonitor:24552 [interfaces.py:start():190] Started disk monitoring
2023-07-17 17:55:51,971 INFO    SystemMonitor:24552 [interfaces.py:start():190] Started memory monitoring
2023-07-17 17:55:52,045 INFO    SystemMonitor:24552 [interfaces.py:start():190] Started network monitoring
2023-07-17 17:55:52,089 DEBUG   HandlerThread:24552 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-17 17:55:52,089 DEBUG   HandlerThread:24552 [system_info.py:probe():240] Probing system done
2023-07-17 17:55:52,089 DEBUG   HandlerThread:24552 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.19045-SP0', 'python': '3.10.4', 'heartbeatAt': '2023-07-17T10:55:51.934137', 'startedAt': '2023-07-17T10:55:50.327643', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'C:\\Users\\motom\\Desktop\\Python\\Sputnik_VAE\\main.py', 'codePath': 'main.py', 'host': 'WS0001', 'username': 'Solsa', 'executable': 'C:\\Users\\motom\\Desktop\\Python\\Sputnik_VAE\\venv\\Scripts\\python.exe', 'cpu_count': 4, 'cpu_count_logical': 8, 'cpu_freq': {'current': 1600.0, 'min': 0.0, 'max': 1800.0}, 'cpu_freq_per_core': [{'current': 1600.0, 'min': 0.0, 'max': 1800.0}], 'disk': {'total': 463.34703063964844, 'used': 422.70462799072266}, 'memory': {'total': 15.810821533203125}}
2023-07-17 17:55:52,089 INFO    HandlerThread:24552 [system_monitor.py:probe():211] Finished collecting system info
2023-07-17 17:55:52,089 INFO    HandlerThread:24552 [system_monitor.py:probe():214] Publishing system info
2023-07-17 17:55:52,090 DEBUG   HandlerThread:24552 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-17 17:55:52,092 DEBUG   HandlerThread:24552 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-17 17:55:52,094 INFO    HandlerThread:24552 [system_monitor.py:probe():216] Finished publishing system info
2023-07-17 17:55:52,133 DEBUG   SenderThread:24552 [sender.py:send():369] send: files
2023-07-17 17:55:52,133 INFO    SenderThread:24552 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-17 17:55:52,162 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: stop_status
2023-07-17 17:55:52,162 DEBUG   SenderThread:24552 [sender.py:send_request():396] send_request: stop_status
2023-07-17 17:55:52,272 INFO    Thread-16 :24552 [dir_watcher.py:_on_file_created():272] file/dir created: C:\Users\motom\Desktop\Python\Sputnik_VAE\wandb\run-20230717_175550-03q3v84h\files\wandb-metadata.json
2023-07-17 17:55:52,274 INFO    Thread-16 :24552 [dir_watcher.py:_on_file_created():272] file/dir created: C:\Users\motom\Desktop\Python\Sputnik_VAE\wandb\run-20230717_175550-03q3v84h\files\wandb-summary.json
2023-07-17 17:55:52,275 INFO    Thread-16 :24552 [dir_watcher.py:_on_file_created():272] file/dir created: C:\Users\motom\Desktop\Python\Sputnik_VAE\wandb\run-20230717_175550-03q3v84h\files\requirements.txt
2023-07-17 17:55:52,612 DEBUG   SenderThread:24552 [sender.py:send():369] send: telemetry
2023-07-17 17:55:53,155 INFO    wandb-upload_0:24552 [upload_job.py:push():133] Uploaded file C:\Users\motom\AppData\Local\Temp\tmpf3y89t72wandb\wb7tqdr5-wandb-metadata.json
2023-07-17 17:55:53,286 INFO    Thread-16 :24552 [dir_watcher.py:_on_file_created():272] file/dir created: C:\Users\motom\Desktop\Python\Sputnik_VAE\wandb\run-20230717_175550-03q3v84h\files\output.log
2023-07-17 17:55:55,305 INFO    Thread-16 :24552 [dir_watcher.py:_on_file_modified():289] file/dir modified: C:\Users\motom\Desktop\Python\Sputnik_VAE\wandb\run-20230717_175550-03q3v84h\files\output.log
2023-07-17 17:55:55,853 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: status_report
2023-07-17 17:55:59,520 INFO    Thread-16 :24552 [dir_watcher.py:_on_file_modified():289] file/dir modified: C:\Users\motom\Desktop\Python\Sputnik_VAE\wandb\run-20230717_175550-03q3v84h\files\output.log
2023-07-17 17:56:01,009 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: status_report
2023-07-17 17:56:06,125 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: status_report
2023-07-17 17:56:07,232 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: stop_status
2023-07-17 17:56:07,234 DEBUG   SenderThread:24552 [sender.py:send_request():396] send_request: stop_status
2023-07-17 17:56:11,652 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: status_report
2023-07-17 17:56:16,671 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: status_report
2023-07-17 17:56:21,817 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: status_report
2023-07-17 17:56:22,128 ERROR   SenderThread:24552 [internal_api.py:execute():324] 409 response executing GraphQL.
2023-07-17 17:56:22,129 ERROR   SenderThread:24552 [internal_api.py:execute():325] {"errors":[{"message":"run soloviy-stanislav/VAE/03q3v84h was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-07-17 17:56:22,184 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: stop_status
2023-07-17 17:56:23,654 ERROR   SenderThread:24552 [internal_api.py:execute():324] 409 response executing GraphQL.
2023-07-17 17:56:23,655 ERROR   SenderThread:24552 [internal_api.py:execute():325] {"errors":[{"message":"run soloviy-stanislav/VAE/03q3v84h was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-07-17 17:56:26,302 ERROR   SenderThread:24552 [internal_api.py:execute():324] 409 response executing GraphQL.
2023-07-17 17:56:26,303 ERROR   SenderThread:24552 [internal_api.py:execute():325] {"errors":[{"message":"run soloviy-stanislav/VAE/03q3v84h was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-07-17 17:56:26,303 INFO    SenderThread:24552 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\venv\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\venv\lib\site-packages\wandb\sdk\internal\internal_api.py", line 321, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\venv\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\venv\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\venv\lib\site-packages\wandb\sdk\lib\gql_request.py", line 56, in execute
    request.raise_for_status()
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2023-07-17 17:56:27,248 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:56:30,629 ERROR   SenderThread:24552 [internal_api.py:execute():324] 409 response executing GraphQL.
2023-07-17 17:56:30,630 ERROR   SenderThread:24552 [internal_api.py:execute():325] {"errors":[{"message":"run soloviy-stanislav/VAE/03q3v84h was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-07-17 17:56:32,325 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:56:37,537 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:56:40,597 ERROR   SenderThread:24552 [internal_api.py:execute():324] 409 response executing GraphQL.
2023-07-17 17:56:40,598 ERROR   SenderThread:24552 [internal_api.py:execute():325] {"errors":[{"message":"run soloviy-stanislav/VAE/03q3v84h was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-07-17 17:56:42,637 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:56:47,698 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:56:52,095 DEBUG   SystemMonitor:24552 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-07-17 17:56:52,836 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:56:57,137 ERROR   SenderThread:24552 [internal_api.py:execute():324] 409 response executing GraphQL.
2023-07-17 17:56:57,138 ERROR   SenderThread:24552 [internal_api.py:execute():325] {"errors":[{"message":"run soloviy-stanislav/VAE/03q3v84h was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-07-17 17:56:58,019 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:57:01,019 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: partial_history
2023-07-17 17:57:03,106 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:57:04,661 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: poll_exit
2023-07-17 17:57:09,694 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:57:14,739 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:57:19,768 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:57:24,833 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:57:29,857 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:57:31,732 ERROR   SenderThread:24552 [internal_api.py:execute():324] 409 response executing GraphQL.
2023-07-17 17:57:31,732 ERROR   SenderThread:24552 [internal_api.py:execute():325] {"errors":[{"message":"run soloviy-stanislav/VAE/03q3v84h was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-07-17 17:57:34,896 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:57:39,928 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:57:44,973 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:57:50,022 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:57:55,062 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:58:00,107 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:58:05,135 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:58:10,164 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:58:15,203 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:58:20,242 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:58:25,276 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:58:30,325 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:58:35,353 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:58:40,387 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:58:45,423 DEBUG   HandlerThread:24552 [handler.py:handle_request():144] handle_request: keepalive
2023-07-17 17:58:48,325 ERROR   SenderThread:24552 [internal_api.py:execute():324] 409 response executing GraphQL.
2023-07-17 17:58:48,325 ERROR   SenderThread:24552 [internal_api.py:execute():325] {"errors":[{"message":"run soloviy-stanislav/VAE/03q3v84h was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-07-17 17:58:48,449 INFO    HandlerThread:24552 [handler.py:finish():854] shutting down handler
2023-07-17 17:58:48,449 INFO    HandlerThread:24552 [system_monitor.py:finish():190] Stopping system monitor
2023-07-17 17:58:48,449 DEBUG   SystemMonitor:24552 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-07-17 17:58:48,450 INFO    HandlerThread:24552 [interfaces.py:finish():202] Joined cpu monitor
2023-07-17 17:58:48,450 DEBUG   SystemMonitor:24552 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-07-17 17:58:48,450 INFO    HandlerThread:24552 [interfaces.py:finish():202] Joined disk monitor
2023-07-17 17:58:48,451 INFO    HandlerThread:24552 [interfaces.py:finish():202] Joined memory monitor
2023-07-17 17:58:48,451 INFO    HandlerThread:24552 [interfaces.py:finish():202] Joined network monitor
2023-07-17 17:58:48,479 INFO    WriterThread:24552 [datastore.py:close():298] close: C:\Users\motom\Desktop\Python\Sputnik_VAE\wandb\run-20230717_175550-03q3v84h\run-03q3v84h.wandb
2023-07-17 17:58:48,820 ERROR   StreamThr :24552 [internal.py:wandb_internal():174] Thread SenderThread:
Traceback (most recent call last):
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\venv\lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\venv\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1822, in upsert_run
    response = self.gql(
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\venv\lib\site-packages\wandb\sdk\internal\internal_api.py", line 293, in gql
    ret = self._retry_gql(
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\venv\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\venv\lib\site-packages\wandb\sdk\internal\internal_api.py", line 321, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\venv\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\venv\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\venv\lib\site-packages\wandb\sdk\lib\gql_request.py", line 56, in execute
    request.raise_for_status()
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\venv\lib\site-packages\wandb\sdk\internal\internal_util.py", line 49, in run
    self._run()
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\venv\lib\site-packages\wandb\sdk\internal\internal_util.py", line 93, in _run
    self._debounce()
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\venv\lib\site-packages\wandb\sdk\internal\internal.py", line 334, in _debounce
    self._sm.debounce()
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\venv\lib\site-packages\wandb\sdk\internal\sender.py", line 527, in debounce
    self._maybe_update_config(always=final)
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\venv\lib\site-packages\wandb\sdk\internal\sender.py", line 504, in _maybe_update_config
    self._debounce_config()
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\venv\lib\site-packages\wandb\sdk\internal\sender.py", line 533, in _debounce_config
    self._api.upsert_run(
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\venv\lib\site-packages\wandb\apis\normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run soloviy-stanislav/VAE/03q3v84h was previously created and deleted; try a new run name (Error 409: Conflict)
